### ISSUE TITLE
Trees / Parse Tree - Operator Module Import

### ISSUE THREAD

**Issue by matt-oconnell** [RunestoneInteractive/pythonds#17]
[Link](http://interactivepython.org/runestone/static/pythonds/Trees/ParseTree.html#lst-eval)

Listing 1 requires explicit import of `operator` module to function correctly. Should this be included in the listing?

`opers = {'+':operator.add, '-':operator.sub, '*':operator.mul, '/':operator.truediv}`

**Comment by adejumool** [comment]
working to fix this 

-Tobi Adejumo, Berea college student 2020
