### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/pythonds#33]
Error reported in course pythonds on page DijkstrasAlgorithm by user CMZ colinzack@gmail.com
I copied the algorithm code and and added in some vertexes and edges like in an earlier chapter but it is always giving the response that the distance is 9223372036854775807:
from pythonds.graphs import PriorityQueue, Graph, Vertex
def dijkstra(aGraph,start):
    start = Vertex(start)
    pq = PriorityQueue()
    start.setDistance(0)
    pq.buildHeap([(v.getDistance(),v) for v in aGraph])
    while not pq.isEmpty():
        currentVert = pq.delMin()
        for nextVert in currentVert.getConnections():
            print("2")
            newDist = currentVert.getDistance() \
                    + currentVert.getWeight(nextVert)
            if newDist < nextVert.getDistance():
                nextVert.setDistance( newDist )
                nextVert.setPred(currentVert)
                pq.decreaseKey(nextVert,newDist)
                
g = Graph()
for i in range(6):
    g.addVertex(i)

g.addEdge(0,1,1)
g.addEdge(0,5,2)
g.addEdge(1,2,4)
g.addEdge(2,3,9)
g.addEdge(3,4,7)
g.addEdge(3,5,3)
g.addEdge(4,0,1)
g.addEdge(5,4,8)
g.addEdge(5,2,1)
start = Vertex(1)
dijkstra(g,start)
print (Vertex(2).getDistance())

**Comment by bnmnetp** [comment]
The line ``print(Vertex(2).getDistance())``. Creates a new vertex and initialized the distance to maxint so you are not looking at the vertex you think you are.
