### ISSUE TITLE
wrong answer

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/pythonds#34]
Error reported in course pythonds on page InfixPrefixandPostfixExpressions by user mmarchese1 mmarchese1@gmail.com
The third self-check problem is to convert "5 * 3 ** (4 - 2)" to postfix.  The correct answer is "5 3 4 2 - ** *", but your webpage is looking for "5 3 4 2 - ^ *".

**Comment by anujinm** [comment]
I think it's fixed. "5 3 4 2 - ** *" seems to be working
