### ISSUE TITLE
Typo in 5.5.1 Hash Functions

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/pythonds#35]
Error reported in course pythonds on page http://interactivepython.org/runestone/static/pythonds/SortSearch/Hashing.html#hash-functions by user anonymous johnyu0424@gmail.com
Hi, in 5.5.1 Hash Functions of Problem Solving with Algorithms and Data Structures using Python, last line of the 4th paragraph. I think you meant to say ..."34"+56+55+64+"10"=219... The 43 and the 01 are not reversed.

**Comment by bnmnetp** [comment]
No, the text says that "every other" number is reversed, not every number.
