### ISSUE TITLE
Merge sort is unstable

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/pythonds#56]
Error reported in course pythonds on page TheMergeSort by user flavianshem flavianshemerirwe@gmail.com
The implementation of the merge sort makes it an unstable sort algorithm. During merging, if two elements from both halves are equal, the left element should be added to the list first before the right element.

**Comment by yasinovskyy** [comment]
This issue was addressed in commit 3302b2351ece6cec666c15d0af3558def364a38b and should be closed.
