### ISSUE TITLE
book mentions chapter 8 but only has 7 chapters

### ISSUE THREAD

**Issue by k4droid3** [RunestoneInteractive/pythonds#58]
![screen shot 2018-10-01 at 8 55 30 pm](https://user-images.githubusercontent.com/18416186/46321417-cd367d00-c600-11e8-8ee9-10df325f7ee8.png)

**Comment by bnmnetp** [comment]
yes, I'll get around to adding the advanced topics chapter one day.

**Comment by codeofdusk** [comment]
Fixed in third edition.
