### ISSUE TITLE
2.4 Anagram detection example solution 1 checking off 

### ISSUE THREAD

**Issue by ThymeLy** [RunestoneInteractive/pythonds#63]
The anagram solution 1 return true when run with print(anagramSolution1('abcd','addcb')).
I think the problem is where after running the stillOK statement that return False, upon exiting if statement, it is assigned stillOK = True, which cause it to enter the while loop even when the length does not match. 

I have added an else statement after the stillOK = False and it returns the expected result. 

def anagramSolution1(s1,s2):
    alist = list(s2)
    pos1 = 0
    if len(s1) != len(s2):
        stillOK = False

    else:
        stillOK = True

    while pos1 < len(s1) and stillOK:
        pos2 = 0
        found = False
        while pos2 < len(alist) and not found:
            if s1[pos1] == alist[pos2]:
                found = True
            else:
                pos2 = pos2 + 1

        if found:
            alist[pos2] = None
        else:
            stillOK = False

        pos1 = pos1 + 1

    return stillOK

**Comment by yasinovskyy** [comment]
Issue addressed in commit abdabefab8820e1c7c14bfa1eb5a903e4ed49917 and should be closed.
