### ISSUE TITLE
confusing 'Connector' logic in Logic Gate Simulator

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/pythonds#64]
Error reported in course pythonds on page ObjectOrientedProgramminginPythonDefiningClasses by user franksmeaton14@gmail.com franksmeaton14@gmail.com
I understand the implementation of the gate classes.
However, I am struggling to see how 'source' is used in the 'setNextPin' function.
I have had a look through Codelens. 
I can see how the ToGate calls the output (self.pinA/B.getfrom().getOuput()) using the Connector but I don't see how the setNextPin function calls the FromGate of the c1 as the source 
Please help if you can
Frank

**Comment by bnmnetp** [comment]
In the connector constructor note the call to `tgate.setNextPin(self)` . So, in the setNextPin method source is the `self` from the connector meaning that source is the connector.

```
    def __init__(self, fgate, tgate):
        self.fromgate = fgate
        self.togate = tgate

        tgate.setNextPin(self)
```
