### ISSUE TITLE
2.1.1 Duplicate ID error

### ISSUE THREAD

**Issue by ErnieWhite** [RunestoneInteractive/pythonds#79]
In [a_proper_python_class.rst](https://github.com/RunestoneInteractive/pythonds/blob/master/_sources/ProperClasses/a_proper_python_class.rst) both activecodes have the same ID.

![Screen Shot 2019-12-22 at 7 08 19 PM](https://user-images.githubusercontent.com/24500045/71329840-c5f1dc80-24ee-11ea-89fd-2f0ead14ab4d.png)

**Comment by bnmnetp** [comment]
Fixed - thanks
