### ISSUE TITLE
3.4.1 Typo in link

### ISSUE THREAD

**Issue by ErnieWhite** [RunestoneInteractive/pythonds#80]
Missing space before :ref: in file [AnAnagramDetectionExample.rst](https://github.com/RunestoneInteractive/pythonds/blob/master/_sources/AlgorithmAnalysis/AnAnagramDetectionExample.rst)

replacement.:ref:`ActiveCode 1 <lst_anagramSolution>`

**Comment by bnmnetp** [comment]
fixed, thanks.
