### ISSUE TITLE
Sorting is done in nlogn time

### ISSUE THREAD

**Issue by MayankGoel28** [RunestoneInteractive/pythonds#90]
In 3.4.2, pythonds there is 'As we will see in a later chapter, sorting is typically either O(n2) or O(nlogn), so the sorting operations dominate the iteration. In the end, this algorithm will have the same order of magnitude as that of the sorting process.'

However, my opinion is that it'll be cleared (and more correct) to consider this is an improvement, as sort is more optimal.

**Comment by bnmnetp** [comment]
I don't understand your issue.

The point of this whole section is to show several options and evaluate them.

**Comment by MayankGoel28** [comment]
It claims that the solution has the same runtime as the previous one, but that was n2 and this is nlogn

**Comment by bnmnetp** [comment]
No it doesn't, it claims that the runtime will depend on the sorting algorithm.  The point of this particular example is to show that you have to look beyond the fact that there is a single loop to compare the lists, i.e. it is not linear.
