### ISSUE TITLE
Solution Manual?

### ISSUE THREAD

**Issue by tas09009** [RunestoneInteractive/pythonds#98]
I've been going through the book along with the practice exercises; it's fantastic. However I can't seem to find any solution manual or answers for the exercises. Does that exist somewhere?

**Comment by bnmnetp** [comment]
No, sorry.  We have always resisted creating a solution manual for this book as there are many possible solutions for most questions.  I empathize with the many overworked and underpaid instructors out there, but I have always been a proponent of the do something before you assign it philosophy.

**Comment by tas09009** [comment]
I understand :(
Thanks for responding
